BUILDSCAD_PROJECT=baseGenerator
BUILDSCAD_VERSION=1.0.0
BUILDSCAD_AUTHOR=dduxx
BUILDSCAD_ASSEMBLIES=scad/main.scad[BASE_TYPE="r";WIDTH=25;DEPTH=25],\
    scad/main.scad[BASE_TYPE="r";WIDTH=28;DEPTH=28],\
    scad/main.scad[BASE_TYPE="r";WIDTH=30;DEPTH=30],\
    scad/main.scad[BASE_TYPE="r";WIDTH=32;DEPTH=32],\
    scad/main.scad[BASE_TYPE="r";WIDTH=40;DEPTH=40],\
    scad/main.scad[BASE_TYPE="r";WIDTH=50;DEPTH=50],\
    scad/main.scad[BASE_TYPE="r";WIDTH=60;DEPTH=60],\
    scad/main.scad[BASE_TYPE="r";WIDTH=70;DEPTH=70],\
    scad/main.scad[BASE_TYPE="r";WIDTH=80;DEPTH=80],\
    scad/main.scad[BASE_TYPE="r";WIDTH=90;DEPTH=90],\
    scad/main.scad[BASE_TYPE="r";WIDTH=100;DEPTH=100],\
    scad/main.scad[BASE_TYPE="r";WIDTH=130;DEPTH=130],\
    scad/main.scad[BASE_TYPE="r";WIDTH=160;DEPTH=160],\
    scad/main.scad[BASE_TYPE="r";WIDTH=60;DEPTH=35],\
    scad/main.scad[BASE_TYPE="r";WIDTH=75;DEPTH=42],\
    scad/main.scad[BASE_TYPE="r";WIDTH=90;DEPTH=52],\
    scad/main.scad[BASE_TYPE="r";WIDTH=105;DEPTH=70],\
    scad/main.scad[BASE_TYPE="r";WIDTH=120;DEPTH=92],\
    scad/main.scad[BASE_TYPE="r";WIDTH=70;DEPTH=25],\
    scad/main.scad[BASE_TYPE="r";WIDTH=170;DEPTH=105],\
    scad/main.scad[BASE_TYPE="r";WIDTH=150;DEPTH=95],\
    scad/main.scad[BASE_TYPE="s";WIDTH=25;DEPTH=25],\
    scad/main.scad[BASE_TYPE="s";WIDTH=28;DEPTH=28],\
    scad/main.scad[BASE_TYPE="s";WIDTH=30;DEPTH=30],\
    scad/main.scad[BASE_TYPE="s";WIDTH=32;DEPTH=32],\
    scad/main.scad[BASE_TYPE="s";WIDTH=40;DEPTH=40],\
    scad/main.scad[BASE_TYPE="s";WIDTH=50;DEPTH=50],\
    scad/main.scad[BASE_TYPE="s";WIDTH=60;DEPTH=60],\
    scad/main.scad[BASE_TYPE="s";WIDTH=70;DEPTH=70],\
    scad/main.scad[BASE_TYPE="s";WIDTH=80;DEPTH=80],\
    scad/main.scad[BASE_TYPE="s";WIDTH=90;DEPTH=90],\
    scad/main.scad[BASE_TYPE="s";WIDTH=100;DEPTH=100],\
    scad/main.scad[BASE_TYPE="s";WIDTH=130;DEPTH=130],\
    scad/main.scad[BASE_TYPE="s";WIDTH=160;DEPTH=160],\
    scad/main.scad[BASE_TYPE="s";WIDTH=60;DEPTH=35],\
    scad/main.scad[BASE_TYPE="s";WIDTH=75;DEPTH=42],\
    scad/main.scad[BASE_TYPE="s";WIDTH=90;DEPTH=52],\
    scad/main.scad[BASE_TYPE="s";WIDTH=105;DEPTH=70],\
    scad/main.scad[BASE_TYPE="s";WIDTH=120;DEPTH=92],\
    scad/main.scad[BASE_TYPE="s";WIDTH=70;DEPTH=25],\
    scad/main.scad[BASE_TYPE="s";WIDTH=170;DEPTH=105],\
    scad/main.scad[BASE_TYPE="s";WIDTH=150;DEPTH=95],\
    scad/main.scad[BASE_TYPE="p";WIDTH=60;DEPTH=35],\
    scad/main.scad[BASE_TYPE="p";WIDTH=75;DEPTH=42],\
    scad/main.scad[BASE_TYPE="p";WIDTH=90;DEPTH=52],\
    scad/main.scad[BASE_TYPE="p";WIDTH=105;DEPTH=70],\
    scad/main.scad[BASE_TYPE="p";WIDTH=120;DEPTH=92],\
    scad/main.scad[BASE_TYPE="p";WIDTH=70;DEPTH=25],\
    scad/main.scad[BASE_TYPE="p";WIDTH=170;DEPTH=105],\
    scad/main.scad[BASE_TYPE="p";WIDTH=150;DEPTH=95]
BUILDSCAD_LOG_LEVEL=INFO
BUILDSCAD_OUTPUT_FORMAT=stl,png
BUILDSCAD_OPENSCAD_COLORSCHEME=Cornfield
BUILDSCAD_IMAGESIZE=1280,720
BUILDSCAD_OPENSCAD_PATH=openscad-nightly
